### ISSUE TITLE
[EPIC] API de Cadastro

### ISSUE THREAD

**Issue by WhiteAngel13** [infinity-js/planning#1]
- [ ] - `Lucienne` deve ser capaz de receber via `API REST` os dados `Nome, Telefone e Senha`
- [ ] - `Lucienne` deve verificar se o número informado já não existe na base de dados
- [ ] - `Lucienne` deve salvar o telefone com um status de `Não Verificado`
- [ ] - `Lucienne` deve usar o RabbitMQ para avisar a Nova que um número de telefone deve ser Validado
- [ ] - `Nova` deve gera um token de 6 dígitos e salva na base de dados, junto com o serviço que pediu a validação e uma expiração de 1h
- [ ] - `Nova` deve usar o RabbitMQ para pedir que `Miguel` envie um SMS para o número de telefone com o token
- [ ] - `Lucienne` deve ser capaz de receber um pedido de verificação de número de telefone, ela repassa para `Nova` perguntando se está correto, caso sim, `Lucienne` verifica o número na sua base de dados e `Nova` apaga o token
